### ISSUE TITLE
chmod'ing /usr/local

### ISSUE THREAD

**Issue by Opennat** [coolaj86/iojs-install-script#2]
> sudo chown -R $(whoami) /usr/local

For what doing this, and, especially, for all undelying directories? This directory by default is root owned for security reasons.

**Comment by coolaj86** [comment]
Yes and No.

The user running the script must be an administrator with `sudo` privileges in the first place and I can't think of any cases where an admin who has sudo access should not be able to write to `/usr/local`.

However, for people who are just getting started with node who will be running either on a VPS or a Macbook, it's important to change the ownership of `/usr/local/` to the administrator so that they don't have to run `npm install` with `sudo`.

Also, on OS X with the node installer changes `/usr/local` which also breaks `brew` and this fixes it.

So if you have special needs for `/usr/local` you shouldn't use this script. This script is intended for average devs.
